[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

; ==== 内存与分区配置 (针对 N16R8) ====
board_build.arduino.memory_type = qio_opi
board_upload.flash_size = 16MB
board_build.partitions = default_16MB.csv

; 开启 8MB PSRAM 支持
build_flags = 
    -DBOARD_HAS_PSRAM

; ==== 硬件调试器配置 ====
; ESP32-S3 自带原生 USB JTAG 调试器
debug_tool = esp-builtin
debug_init_break = tbreak setup
build_type = debug
; 如果你要用内置 USB 直接烧录，取消下面这行的注释
; upload_protocol = esp-builtin


